//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolent.Models.Resource.Shared {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evolent.Models.Resource.Shared.ExceptionMessages", typeof(ExceptionMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Application Token.
        /// </summary>
        public static string ERROR1000 {
            get {
                return ResourceManager.GetString("ERROR1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid User Token.
        /// </summary>
        public static string ERROR1001 {
            get {
                return ResourceManager.GetString("ERROR1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Application and User Token.
        /// </summary>
        public static string ERROR1002 {
            get {
                return ResourceManager.GetString("ERROR1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Request Token Authentication Failure.
        /// </summary>
        public static string ERROR1003 {
            get {
                return ResourceManager.GetString("ERROR1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Login Credentials.
        /// </summary>
        public static string ERROR1010 {
            get {
                return ResourceManager.GetString("ERROR1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Validation Failed.
        /// </summary>
        public static string ERROR1020 {
            get {
                return ResourceManager.GetString("ERROR1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Failed to save contact details.
        /// </summary>
        public static string ERROR1027 {
            get {
                return ResourceManager.GetString("ERROR1027", resourceCulture);
            }
        }
    }
}
